using System;
using System.Collections.Generic;

namespace JBHRIS.Api.Dal.JBHR
{
    public partial class USys
    {
        public int Auto { get; set; }
        public string Company { get; set; }
        public string Compaddr { get; set; }
        public string Comptel { get; set; }
        public string Compfax { get; set; }
        public string Complabid { get; set; }
        public string Comphelid { get; set; }
        public string Compid { get; set; }
        public string Compman { get; set; }
        public string Helorgname { get; set; }
        public string Ff103 { get; set; }
        public string Ff0407 { get; set; }
        public string Companybankac { get; set; }
        public string Companybankno { get; set; }
        public string Bankno { get; set; }
        public string Sysdisk { get; set; }
        public string Company1 { get; set; }
        public string Compid1 { get; set; }
        public string Ff04071 { get; set; }
        public string Welsalcode { get; set; }
        public decimal? Welpay { get; set; }
        public int? Attmonth { get; set; }
        public string Eatsalcode { get; set; }
        public string Foodsalcode { get; set; }
        public string Empsalcode { get; set; }
        public int? Inday { get; set; }
        public string Ondutysalcode { get; set; }
        public decimal? Ondutyamt { get; set; }
        public string Attawardsalcode { get; set; }
        public decimal? Attmonamt { get; set; }
        public decimal? Attqty { get; set; }
        public decimal? Attqty1 { get; set; }
        public decimal? Attamt { get; set; }
        public decimal? Attamt1 { get; set; }
        public decimal? Lattqty { get; set; }
        public decimal? Lattqty1 { get; set; }
        public decimal? Lattamt { get; set; }
        public decimal? Lattamt1 { get; set; }
        public decimal? Fattqty { get; set; }
        public decimal? Fattqty1 { get; set; }
        public decimal? Fattamt { get; set; }
        public decimal? Fattamt1 { get; set; }
        public decimal? Ljobper { get; set; }
        public decimal? Ljobper1 { get; set; }
        public decimal? Retirerate { get; set; }
        public decimal? Retirerate1 { get; set; }
        public decimal? Nretirerate { get; set; }
        public decimal? Nretirerate1 { get; set; }
        public string Retsalcode { get; set; }
        public string Notaxsalcode { get; set; }
        public string Totaxsalcode { get; set; }
        public string Otfoodsalcode { get; set; }
        public string Otfoodsalcode1 { get; set; }
        public string Ottrasalcode { get; set; }
        public decimal? Malemaxhrs { get; set; }
        public decimal? Femalemaxhrs { get; set; }
        public decimal? Otunit { get; set; }
        public string Lsalcode { get; set; }
        public string Laboversalcode { get; set; }
        public string Labrepairsalcode { get; set; }
        public string Hsalcode { get; set; }
        public decimal? Empfamilycnt { get; set; }
        public decimal? Compersoncnt { get; set; }
        public decimal? Heacomprate { get; set; }
        public string Healthoversalcode { get; set; }
        public string Healthrepairsalcode { get; set; }
        public string Groupsalcd { get; set; }
        public decimal? Groupexp1 { get; set; }
        public decimal? Groupexp2 { get; set; }
        public decimal? Groupexp51 { get; set; }
        public decimal? Groupexp52 { get; set; }
        public string Cardtype { get; set; }
        public string Cardfilename { get; set; }
        public int? NobrPos { get; set; }
        public int? NobrLen { get; set; }
        public int? SerPos { get; set; }
        public int? SerLen { get; set; }
        public int? DatePos { get; set; }
        public int? DateLen { get; set; }
        public int? TimePos { get; set; }
        public int? TimeLen { get; set; }
        public string Carddateformat { get; set; }
        public bool? Cardnoeuqalnobr { get; set; }
        public int? Specialcaltype { get; set; }
        public decimal? Year11 { get; set; }
        public decimal? Year12 { get; set; }
        public decimal? Vacationdays01 { get; set; }
        public decimal? Year21 { get; set; }
        public decimal? Year22 { get; set; }
        public decimal? Vacationdays02 { get; set; }
        public decimal? Year31 { get; set; }
        public decimal? Year32 { get; set; }
        public decimal? Vacationdays03 { get; set; }
        public decimal? Year41 { get; set; }
        public decimal? Year42 { get; set; }
        public decimal? Vacationdays04 { get; set; }
        public decimal? Year51 { get; set; }
        public decimal? Nextyearday { get; set; }
        public int? Maxdays { get; set; }
        public int? Yearbase { get; set; }
        public int? Year0type1 { get; set; }
        public decimal? Year01 { get; set; }
        public int? Year0efftype1 { get; set; }
        public decimal? Month01day1 { get; set; }
        public decimal? Month02day1 { get; set; }
        public decimal? Month03day1 { get; set; }
        public decimal? Month04day1 { get; set; }
        public decimal? Month05day1 { get; set; }
        public decimal? Month06day1 { get; set; }
        public decimal? Month07day1 { get; set; }
        public decimal? Month08day1 { get; set; }
        public decimal? Month09day1 { get; set; }
        public decimal? Month10day1 { get; set; }
        public decimal? Month11day1 { get; set; }
        public decimal? Month12day1 { get; set; }
        public int? Year0type2 { get; set; }
        public decimal? Year02 { get; set; }
        public int? Year0efftype2 { get; set; }
        public decimal? Month01day2 { get; set; }
        public decimal? Month02day2 { get; set; }
        public decimal? Month03day2 { get; set; }
        public decimal? Month04day2 { get; set; }
        public decimal? Month05day2 { get; set; }
        public decimal? Month06day2 { get; set; }
        public decimal? Month07day2 { get; set; }
        public decimal? Month08day2 { get; set; }
        public decimal? Month09day2 { get; set; }
        public decimal? Month10day2 { get; set; }
        public decimal? Month11day2 { get; set; }
        public decimal? Month12day2 { get; set; }
        public int? Year0type3 { get; set; }
        public decimal? Year03 { get; set; }
        public int? Year0efftype3 { get; set; }
        public decimal? Month01day3 { get; set; }
        public decimal? Month02day3 { get; set; }
        public decimal? Month03day3 { get; set; }
        public decimal? Month04day3 { get; set; }
        public decimal? Month05day3 { get; set; }
        public decimal? Month06day3 { get; set; }
        public decimal? Month07day3 { get; set; }
        public decimal? Month08day3 { get; set; }
        public decimal? Month09day3 { get; set; }
        public decimal? Month10day3 { get; set; }
        public decimal? Month11day3 { get; set; }
        public decimal? Month12day3 { get; set; }
        public int? Year0type4 { get; set; }
        public decimal? Year04 { get; set; }
        public int? Year0efftype4 { get; set; }
        public decimal? Month01day4 { get; set; }
        public decimal? Month02day4 { get; set; }
        public decimal? Month03day4 { get; set; }
        public decimal? Month04day4 { get; set; }
        public decimal? Month05day4 { get; set; }
        public decimal? Month06day4 { get; set; }
        public decimal? Month07day4 { get; set; }
        public decimal? Month08day4 { get; set; }
        public decimal? Month09day4 { get; set; }
        public decimal? Month10day4 { get; set; }
        public decimal? Month11day4 { get; set; }
        public decimal? Month12day4 { get; set; }
        public int? Taxtype { get; set; }
        public decimal? Stdeduetamtnmar { get; set; }
        public decimal? Stdeduetamtmar { get; set; }
        public decimal? Taxfree70down { get; set; }
        public decimal? Taxfree70up { get; set; }
        public decimal? Salarydedutamt { get; set; }
        public string Taxsalcode { get; set; }
        public decimal? Taxamtamonth { get; set; }
        public decimal? Fixtaxrate { get; set; }
        public decimal? Nettaxamt01 { get; set; }
        public decimal? Nettaxamt02 { get; set; }
        public decimal? Nettaxamt03 { get; set; }
        public decimal? Nettaxamt04 { get; set; }
        public decimal? Nettaxamt05 { get; set; }
        public decimal? Nettaxamt06 { get; set; }
        public decimal? Nettaxamt07 { get; set; }
        public decimal? Nettaxamt08 { get; set; }
        public decimal? Nettaxamt09 { get; set; }
        public decimal? Nettaxamt10 { get; set; }
        public decimal? Nettaxrate01 { get; set; }
        public decimal? Nettaxrate02 { get; set; }
        public decimal? Nettaxrate03 { get; set; }
        public decimal? Nettaxrate04 { get; set; }
        public decimal? Nettaxrate05 { get; set; }
        public decimal? Addupamt01 { get; set; }
        public decimal? Addupamt02 { get; set; }
        public decimal? Addupamt03 { get; set; }
        public decimal? Addupamt04 { get; set; }
        public decimal? Addupamt05 { get; set; }
        public decimal? Forsalbasd { get; set; }
        public decimal? Fortaxrate03 { get; set; }
        public decimal? Entryday { get; set; }
        public decimal? Fortaxrate01 { get; set; }
        public decimal? Fortaxrate02 { get; set; }
        public string Smtpserver { get; set; }
        public string Sendmail { get; set; }
        public string Smtpid { get; set; }
        public string Smtppw { get; set; }
    }
}
